# Generated by Django 5.2.10 on 2026-01-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artifact_rawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='External patient identifier', max_length=50)),
                ('test_code', models.CharField(help_text='LOINC or internal test code', max_length=50)),
                ('test_name', models.CharField(help_text='Human-readable test name', max_length=255)),
                ('result_value', models.DecimalField(decimal_places=2, help_text='Numeric result value', max_digits=10)),
                ('result_unit', models.CharField(help_text='Unit of measurement (e.g., mg/dL)', max_length=20)),
                ('reference_range', models.CharField(blank=True, help_text="Reference range (e.g., '70-100')", max_length=50, null=True)),
                ('performed_at', models.DateTimeField(help_text='When the test was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-performed_at'],
                'constraints': [models.UniqueConstraint(fields=('patient_id', 'test_code', 'performed_at'), name='unique_lab_result')],
            },
        ),
    ]
